build: off

environment:
  PYTHON: "C:\\Python37-x64"

  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      ARCH_BUILD: x86_64
      ARCH: x86_64

install:
  - set PATH=%PYTHON%/Scripts;%PYTHON%;%PATH%
  - pip.exe install --upgrade conan
  - pip.exe install --upgrade sesame-package-tools conan-package-tools bincrafters-package-tools
  - conan user

test_script:
  - sesame build --windows --upload
